server:
  port: 16680
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: pg-jpa-dbpaas-scheduler
  datasource:
    url: jdbc:postgresql://192.168.1.110:5432/db_paas
    username: paas
    password: paas
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect


eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.103:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
