-- public.test definition

-- Drop table

-- DROP TABLE public.test;

CREATE TABLE public.test (
	"content" text NULL,
	id serial4 NOT NULL
);
CREATE INDEX test_id_idx ON public.test (id int4_ops);



CREATE TABLE public.cctv_news (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"content" text NULL,
	"date" date NULL,
	CONSTRAINT cctv_news_pkey PRIMARY KEY (id)
);